### ISSUE TITLE
Create a script to simplify updating to newer versions and testing it

### ISSUE THREAD

**Issue by arothuis** [HarryET/gleam-chocolatey#2]
According to @lpil in the Gleam discord, we can assume the new naming convention for Gleam releases is based on LLVM's / Rust's target triples.

This means we will always be able to replace `%GLEAM_VERSION%` here and get the correct result (e.g. with `v0.24.0`):
* Release ZIP: `https://github.com/gleam-lang/gleam/releases/download/%GLEAM_VERSION%/gleam-%GLEAM_VERSION%-x86_64-pc-windows-msvc.zip`
* SHA512 hash: `https://github.com/gleam-lang/gleam/releases/download/%GLEAM_VERSION%/gleam-%GLEAM_VERSION%-x86_64-pc-windows-msvc.zip.sha512`

This potentially allows for automating some tasks:
1. We could create a script that automatically replaces the version numbers in the package declaration.
1. We could also create a GitHub Action or bot that periodically checks for updates, runs aforementioned script and create a PR.

**Comment by HarryET** [comment]
This has now been done! Thanks for the PRs over a few months and sorry I never got too them - this repo should now be self sustaining and automatically release ~1hr after a release over on the main repo

**Comment by arothuis** [comment]
No problem @HarryET ! Thanks for your work, awesome 👍
